class_path: mamba_mic.system.System
init_args:
  net:
    class_path: monai.networks.nets.dynunet.DynUNet
    init_args:
      spatial_dims: 3
      in_channels: 3
      out_channels: 1
      kernel_size:
        - - 3
          - 3
          - 1
        - - 3
          - 3
          - 3
        - - 3
          - 3
          - 3
        - - 3
          - 3
          - 3
        - - 3
          - 3
          - 3
        - - 3
          - 3
          - 3
      strides:
        - - 1
          - 1
          - 1
        - - 2
          - 2
          - 1
        - - 2
          - 2
          - 2
        - - 2
          - 2
          - 2
        - - 2
          - 2
          - 2
        - - 2
          - 2
          - 1
      upsample_kernel_size:
        - - 2
          - 2
          - 1
        - - 2
          - 2
          - 2
        - - 2
          - 2
          - 2
        - - 2
          - 2
          - 2
        - - 2
          - 2
          - 1
  val_inferer:
    class_path: monai.inferers.SlidingWindowInferer
    init_args:
      roi_size: [192, 192, 48]
      sw_batch_size: 2
      overlap: 0.5
      mode: gaussian
