class_path: mamba_mic.camus_module.System
init_args:
  # include_background: false
  # softmax: true
  # num_output_channels: 4
  criterion:
    class_path: monai.losses.DiceCELoss
    init_args:
      include_background: true
      sigmoid: true
  net:
    class_path: monai.networks.nets.dynunet.DynUNet
    init_args:
      spatial_dims: 2
      in_channels: 1
      out_channels: 1
      filters: [32, 64, 128, 256, 512, 512]
      kernel_size:
      - [3, 3]
      - [3, 3]
      - [3, 3]
      - [3, 3]
      - [3, 3]
      - [3, 3]
      strides:
      - [1, 1]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      upsample_kernel_size:
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
