class_path: mamba_mic.camus_module.System
init_args:
  include_background: false
  softmax: true
  num_output_channels: 4
  criterion:
    class_path: monai.losses.DiceFocalLoss
    init_args:
      include_background: false
      gamma: 1.0
      softmax: true
      squared_pred: true
  net:
    class_path: monai.networks.nets.dynunet.DynUNet
    init_args:
      spatial_dims: 2
      in_channels: 1
      out_channels: 4
      kernel_size:
      - [3, 3]
      - [3, 3]
      - [3, 3]
      - [3, 3]
      - [3, 3]
      - [3, 3]
      - [3, 3]
      - [3, 3]
      strides:
      - [1, 1]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      upsample_kernel_size:
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
      - [2, 2]
