class_path: system.System
init_args:
  net:
    class_path: monai.networks.nets.dynunet.DynUNet
    init_args:
      spatial_dims: 3
      in_channels: 4
      out_channels: 3
      kernel_size: [3, 3, 3, 3, 3]
      strides: [1, 2, 2, 2, 2]
      upsample_kernel_size: [2, 2, 2, 2]
  val_inferer:
    class_path: monai.inferers.SlidingWindowInferer
    init_args:
      roi_size: [128, 128, 128]
      sw_batch_size: 4
      overlap: 0.5
      mode: gaussian