class_path: system.System
init_args:
  include_background: true
  log_hd95: true
  do_slice_inference: true
  slice_shape: [256, 256]
  slice_dim: 2
  slice_batch_size: 32
  net:
    class_path: monai.networks.nets.dynunet.DynUNet
    init_args:
      spatial_dims: 2
      in_channels: 3
      out_channels: 1
      kernel_size:
        - - 3
          - 3
        - - 3
          - 3
        - - 3
          - 3
        - - 3
          - 3
        - - 3
          - 3
        - - 3
          - 3
        - - 3
          - 3
      strides:
        - - 1
          - 1
        - - 2
          - 2
        - - 2
          - 2
        - - 2
          - 2
        - - 2
          - 2
        - - 2
          - 2
        - - 2
          - 2
      upsample_kernel_size:
        - - 2
          - 2
        - - 2
          - 2
        - - 2
          - 2
        - - 2
          - 2
        - - 2
          - 2
        - - 2
          - 2
