class_path: system.System
init_args:
  softmax: true
  include_background: false
  num_output_channels: 3
  log_hd95: false
  net:
    class_path: monai.networks.nets.SegResNet
    init_args:
      in_channels: 1
      out_channels: 3
      spatial_dims: 3
      init_filters: 32
      blocks_down: [1, 2, 2, 4]
      blocks_up: [1, 1, 1]
  val_inferer:
    class_path: monai.inferers.SlidingWindowInferer
    init_args:
      roi_size: [192, 192, 48]
      sw_batch_size: 2
      overlap: 0.5
      mode: gaussian
