class_path: mamba_mic.system.System
init_args:
  net:
    class_path: monai.networks.nets.SegResNet
    init_args:
      in_channels: 3
      out_channels: 1
      spatial_dims: 3
      init_filters: 32
      blocks_down: [1, 2, 2, 4]
      blocks_up: [1, 1, 1]
  val_inferer:
    class_path: monai.inferers.SlidingWindowInferer
    init_args:
      roi_size: [256, 256, 32]
      sw_batch_size: 4
      overlap: 0.5
      mode: gaussian
