class_path: system.System
init_args:
  net:
    class_path: monai.networks.nets.SegResNetVAE
    init_args:
      input_image_size: [128, 128, 128]
      in_channels: 4
      out_channels: 4
      spatial_dims: 3
      vae_nz: 256
      init_filters: 32
      blocks_down: [1, 2, 2, 4]
      blocks_up: [1, 1, 1]
  val_inferer:
    class_path: monai.inferers.SlidingWindowInferer
    init_args:
      roi_size: [128, 128, 128]
      sw_batch_size: 2
      overlap: 0.5
      mode: gaussian
