class_path: mamba_mic.camus_module.System
init_args:
  include_background: true
  softmax: false
  # num_output_channels: 4
  criterion:
    class_path: monai.losses.DiceCELoss
    init_args:
      include_background: true
      sigmoid: true
  net:
    class_path: monai.networks.nets.SegResNet
    init_args:
      in_channels: 1
      out_channels: 1
      spatial_dims: 2
      init_filters: 32
      blocks_down: [1, 2, 2, 4]
      blocks_up: [1, 1, 1]
