class_path: mamba_mic.camus_module.System
init_args:
  include_background: false
  softmax: true
  num_output_channels: 4
  criterion:
    class_path: monai.losses.DiceFocalLoss
    init_args:
      include_background: false
      gamma: 1.0
      softmax: true
      squared_pred: true
  net:
    class_path: monai.networks.nets.SegResNet
    init_args:
      in_channels: 1
      out_channels: 4
      spatial_dims: 2
      init_filters: 32
      blocks_down: [1, 2, 2, 4]
      blocks_up: [1, 1, 1]
