class_path: mamba_mic.camus_module.System
init_args:
  include_background: false
  softmax: true
  num_output_channels: 4
  criterion:
    class_path: monai.losses.DiceCELoss
    init_args:
      include_background: false
      softmax: true
  net:
    class_path: monai.networks.nets.SwinUNETR
    init_args:
      spatial_dims: 2
      img_size: [128, 128]
      in_channels: 1
      out_channels: 4
      feature_size: 48
      depths: [2, 2, 4, 2]
      num_heads: [6, 12, 24, 48]