class_path: models.unet.UNetModel
init_args:
  unet:
    class_path: monai.networks.nets.unet.UNet
    init_args:
      spatial_dims: 3
      in_channels: 4
      out_channels: 3
      channels: [8, 16, 32, 64]
      strides: [2, 2, 2]