class_path: mamba_mic.camus_module.System
init_args:
  include_background: false
  softmax: true
  num_output_channels: 4
  criterion:
    class_path: monai.losses.DiceCELoss
    init_args:
      include_background: false
      softmax: true
  net:
    class_path: monai.networks.nets.UNet
    init_args:
      spatial_dims: 2
      in_channels: 1
      out_channels: 4
      channels: [32, 64, 128, 256, 512]
      strides: [2, 2, 2, 2]
