class_path: mamba_mic.system.System
init_args:
  include_background: true
  do_slice_inference: true
  slice_shape: [384, 384]
  slice_dim: 2
  slice_batch_size: 24
  net:
    class_path: mamba_mic.models.unet.UNet
    init_args: 
      encoder:
        class_path: mamba_mic.models.vssd.Backbone_VSSD
        init_args:
          img_size: 384
          patch_size: 4
          num_classes: 1
          in_chans: 9
          embed_dim: 64
          depths: [2, 4, 8, 4]
          num_heads: [2, 4, 8, 16]
          mlp_ratio: 4.0
          qkv_bias: true
          drop_rate: 0.0
          drop_path_rate: 0.2
      decoder:
        class_path: mamba_mic.models.swin_umamba.UNetResDecoder
        init_args:
          num_classes: 1
          deep_supervision: false
          features_per_stage: [64, 128, 256, 512]
          drop_path_rate: 0.2
          d_state: 64
     
