class_path: mamba_mic.camus_module.CAMUSModule
init_args:
  # include_background: false
  # softmax: true
  # num_output_channels: 4
  criterion:
    class_path: monai.losses.DiceCELoss
    init_args:
      include_background: true
      sigmoid: true
  net:
    class_path: mamba_mic.models.unet.UNet
    init_args: 
      encoder:
        class_path: mamba_mic.models.vssd.Backbone_VMAMBA2
        init_args:
          img_size: 128
          patch_size: 4
          num_classes: 1
          in_chans: 1
          embed_dim: 64
          depths: [2, 4, 8, 4]
          num_heads: [2, 4, 8, 16]
          attn_types: ["mamba2", "mamba2", "mamba2", "mamba2"]
          simple_patch_embed: true
      decoder:
        class_path: mamba_mic.models.swin_umamba.UNetResDecoder
        init_args:
          num_classes: 1
          deep_supervision: false
          features_per_stage: [64, 128, 256, 512]
          drop_path_rate: 0.2
          d_state: 16
          patch_size: 4