wandb:
  project: brats2024
  name: example
trainer:
  max_epochs: 500
  devices: auto
  accelerator: auto
  # max_time: 00:12:00:00
  precision: 32
  log_every_n_steps: 5
  check_val_every_n_epoch: 5
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        log_model: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 2
        monitor: val_loss
        mode: min
        filename: model-{epoch:02d}-{val_loss:.2f}
        verbose: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0004
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 500
    eta_min: 0.000001
